### ISSUE TITLE
Improve support for uberjar applications

### ISSUE THREAD

**Issue by martin-g** [l0rdn1kk0n/wicket-webjars#37]
Spring Boot applications may have either `.war` or `.jar` extension.
We have to support `.jar` too.

See https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/556 and https://github.com/l0rdn1kk0n/wicket-webjars/issues/34

**Comment by MarcGiffing** [comment]
This code works with the ueberjar and the current placeholder:
https://github.com/MarcGiffing/wicket-webjars/tree/wicket7
What do you think?

**Comment by martin-g** [comment]
I'll take a look later today!
Thank you!

**Comment by martin-g** [comment]
@MarcGiffing Please create a Pull Request!

**Comment by MarcGiffing** [comment]
With your code change the ClasspathAssetPathCollector is called multiple times for each jar. But it must only be called once. You introduced a possible perfomance problem if multiple jars are present. I removed the interface on purpose. I'm not sure if you aware of it and readded it also on purpose :)

**Comment by martin-g** [comment]
I've just made it looking like the others.
I've tested it with the SpringBoot application from the original bug report and the time to start was 5secs, so I didn't check further.
Let me take a look with the debugger!

**Comment by martin-g** [comment]
The URLs have been collected earlier in `de.agilecoders.wicket.webjars.collectors.AssetsMap#listWebjarsParentURLs()`.
I've improved `de.agilecoders.wicket.webjars.collectors.ClasspathAssetPathCollector#collect()` to collect just the resources for the currently being processed URL.

Thanks for catching this!

**Comment by steveluo** [comment]
I still have problem to load bootstrap.js when packaged in a uber jar with spring boot. 
Would you please tell me in which version has this issue been fixed?

**Comment by martin-g** [comment]
Thanks for asking!
It appears that I have forgotten to release it!
I'll release 0.4.9 and 0.5.4 now!

**Comment by zhenyuluo** [comment]
@martin-g cool! Thank you so much.

**Comment by martin-g** [comment]
Done!
They should be at Maven Central soon.
Please report whether or not the problem is solved. Thank you!

**Comment by zhenyuluo** [comment]
Hi @martin-g, the issue is fixed. Thank you so much!

**Comment by martin-g** [comment]
:+1:

**Comment by steveluo** [comment]
Hi @martin-g, I still don't see wicket-webjars 0.5.4 in maven central repository. Are you sure it is published?

**Comment by martin-g** [comment]
It was stuck in Sonatype OSS Nexus...
It should be OK now!

**Comment by mpostelnicu** [comment]
working perfectly ! thanks @martin-g !

**Comment by steveluo** [comment]
Yes, it is now working perfectly! Thanks @martin-g !
